### PR TITLE
Compile index.js to ES15 with babel

### PR DESCRIPTION
**Pull request by thechrisnixon**
I am having the same issue as @Dkra https://github.com/inferusvv/react-odometerjs/issues/1.

However, instead of compiling it locally and putting it in github, take advantage of `prepublish` hook getting called when you run `npm publish`. See the `package.json`.

Here is more info https://booker.codes/how-to-build-and-publish-es6-npm-modules-today-with-babel/

### CODE REVIEW

**Comment by Dkra** [comment]
For the folks who facing the same issue, you are able to install a temporary package: 
`npm install react-odometer1js`.
I'll unpublish react-odometer1js package after @inferusvv merge this fix.

**Comment by bezenson** [comment]
@dasnixon Thank you  for helping! I'll check today or tomorrow and merge it

**Comment by thechrisnixon** [comment]
Awesome thanks @inferusvv. I didn't look much into this, nor do I know the proper way, but be nice to figure out a way to make the styles "importable". I'll look into it if I have time.

**Comment by bezenson** [comment]
@dasnixon @Dkra PR merged. Thanks! 👍

**Pull request merged**
